### ISSUE TITLE
Add missing fields to the User Profile

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/saas#16]
Hello @RKB271189 ,

On the page `/user/profile`, there is a `Profile Information` form, we need to make adjustments to it to include the following: 

1. First Name (required)
2. Last Name (required)
3. Phone (not  required)
4. Job Title (drop-down list with these values `Developer, Marketer, Designer, Project Manager, Billing Manager, IT Professional, Executive, None of these `)
5. Employer (drop-down list with these values `Myself, freelance, Myself, full-time, Agency, Business/In-house`)
6. Experience (drop-down list with these values `I am a beginner, I have some experience, I feel comfortable with most Mautic-related tasks, I am an expert`
7. Company Name (not required)

You need to create the form, validators, and edit the controller to save the information

**Comment by mabumusa1** [comment]
The fields and the validators are there. needs testing

**Comment by mabumusa1** [comment]
@SalemCode8 I added the fields but there is still a bug for dropdowns, they do not select the saved value nor update,  please check it out. 

The code is under `bug_fixes`

**Comment by SalemCode8** [comment]
Bug fixed the dropdowns are now working

**Comment by mabumusa1** [comment]
This issue has be solved and merged
