### ISSUE TITLE
Requests to Kub8 needs error handling

### ISSUE THREAD

**Issue by SalemCode8** [mabumusa1/saas#232]
**Describe the bug**
If the user did any actions that will require connection to Kub8 API
and the API respond with for example 500 the user will get the curl error.

**To Reproduce**
1. Disable the kub8 API
2. Go to 'sites list'
3. Click on 'delete install'
4. confirm the delete action
5. See error

**Expected behavior**
As a suggestion:
make all the kub8 requests run in the queue
each action in kub8 API must return webhook request with the request status

**Screenshots**
![image](https://user-images.githubusercontent.com/28122676/167243539-55c59874-6e56-4677-b298-fc42b1c84a7a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mabumusa1** [comment]
Thanks @SalemCode8, I am working on mock to be included inside the ddev image so these errors does not occur

**Please make the requests in a queue**, I agree with you this is important
