### ISSUE TITLE
Minor UI issues on Sites and Groups

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/saas#31]
Thanks, @SalemCode8 for the work you have done so far.

Please fix the following notes: 

- We need a modal to confirm the delete of a site and group before the actual delete action happens
- Please show flash messages when a group is created, edited, and deleted.
- After the edit or create of a group, please redirect to that group.

After these changes PR #30 will be ready to be merged to dev

**Comment by mabumusa1** [comment]
@SalemCode8 I merged PR #30 to fix other issues, the branch is still active to solve these issues

**Comment by SalemCode8** [comment]
@mabumusa1 All Done

**Comment by mabumusa1** [comment]
@SalemCode8 I can not find new commits, where did you push?

**Comment by SalemCode8** [comment]
@mabumusa1 It must be in sites branch
