### ISSUE TITLE
Remove Message on Registration Page

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/saas#90]
On the registration page, there is a Javascript message that shows as modal, we do not want to show this message, it is annoying 

Let's switch it an error bag, when the request is returned.

![image](https://user-images.githubusercontent.com/12627658/157089303-ea7bf3c8-72bf-4875-8522-013999f95e04.png)

**Comment by SalemCode8** [comment]
@mabumusa1 fixed, branch name is `registration_message`
