### ISSUE TITLE
On Register page, the errors of the backend are showing on the ajax requests

### ISSUE THREAD

**Issue by mabumusa1** [mabumusa1/saas#99]

**Comment by SalemCode8** [comment]
@mabumusa1 I didn't get that well, 

can you please explain more ?

**Comment by mabumusa1** [comment]
here we are showing exceptions 

https://github.com/mabumusa1/saas/blob/dev/resources/assets/extended/js/custom/authentication/sign-up/general.js#L142

**Comment by SalemCode8** [comment]
ok, this error has fixed and uploaded in the `register` branch
